const mongoose = require("mongoose");

const learningPathSchema = new mongoose.Schema({

    // User who owns this learning path
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true
    },

    // Original message sent by the user
    message: {
        type: String,
        required: true
    },

    // Profile generated by Python
    profile: {
        type: Object
    },

    // Recommendation generated by Python
    recommendation: {
        type: Object
    }

}, {
    timestamps: true
});

module.exports = mongoose.model("LearningPath", learningPathSchema);